# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "home"
  url = "#about"
  weight = 1

[[main]]
  name = "say hello"
  url = "#contact"
  weight = 2

[[main]]
  name = "talks"
  url = "#talks"
  weight = 3

[[main]]
  name = "publications"
  url = "#publications_featured"
  weight = 4
  
#[[main]]
#  name = "publications"
#  url = "#publications"
#  weight = 4
  
#[[main]]
#  name = "teaching"
#  url = "#teaching"
#  weight = 5
  
#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 3

#[[main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 5

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
   name = "CV"
   url = "files/Amanda_Zheutlin_CV_March2019.pdf"
   weight = 6
